# Generated by Django 5.2.17 on 2026-09-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_document_document_attachments_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='notification_frequency',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='notification_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='notifications_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
