# Generated by Django 5.2.17 on 2026-09-16 08:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_document_document_attachments_gin'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='primary key for the record as UUID', primary_key=True, serialize=False, verbose_name='id')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='date and time at which a record was created', verbose_name='created on')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='date and time at which a record was last updated', verbose_name='updated on')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'impress_document_contribution',
                'constraints': [models.UniqueConstraint(fields=('document', 'user'), name='unique_document_contribution_user')],
            },
        ),
    ]
