# Generated by Django 5.2.17 on 2026-09-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_documentversion'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_id'), name='unique_document_storage_version'),
        ),
        migrations.AlterModelTable(
            name='documentversion',
            table='impress_document_version',
        ),
    ]
