# Generated by Django 5.2.17 on 2026-09-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_notificationsetting'),
        ('core', '0036_documentversion_unique_document_storage_version_and_more'),
    ]

    operations = [
    ]
